//*****MATCH CASE FOR A TRADITIONAL CHECK */

// var regex = /is/;                       // A REGEX THAT CAN BE USED TO MATCH AGAINST SOME OTHER STRING. THE REGEX IS DEFINED BY //, WITH THE CASE TO MATCH WITHIN THE SLASHES. IN THIS CASE, THIS WILL BE USED TO MATCH-CASE THE WORD "is"
// var string = "Regex is great!";         // THE STRING VARIABLE THAT WILL BE USED AGAINST THE REGEX CHECK

// var result = string.match(regex);       // UP UNTIL NOW, NO jQUERY HAS BEEN USED. HERE, THIS CHANGES. JAVASCRIPT CAN BE USED, BUT jQUERY'S MATCH MAKES IT EASIER HERE.
                                           // LINE 15 MEANS - MATCH THE VARIABLE string CONTENTS ACCORDING TO THE REGEX VARIABLE AND PARSE THE CONTENTS (EITHER TRUE - THE VALUE, OR FALSE - null, TO THE result VARIABLE)
// alert(result);    

// WHEN THE REGEX MATCH IS TRUE, THE RESULT OUTPUT WILL BE THE MATCH CASE
// IF THE REGEX CASE TO MATCH IS DIFFERENT TO THE STRING CONTENTS (OR VICE VERSA), alert WILL PASS THE RESULT null - ie. REGEX IS NOT MATCHED WITH THE STRING

//*****MATCH CASE FOR CASE INSENSITIVITIES */

// var regex = /Great/i;                  // REGEX MATCH CASES ARE CASE SENSITIVE. TO OMIT THIS, APPEND THE i FLAG TO THE OUTSIDE
// var string = "Regex is grE!";

// var result = string.match(regex);
// alert(result);                         // THE STRING, OR null IN THIS CASE, WILL THEN BE OUTPUTTED

// NB. THE LETTERS MUST STILL BE PRESENT FOR THE MATCH TO BE PRESENT, IRRESPECTIVE OF CASE IN THIS INSTANCE. "Regex is GrE" WILL RETURN A null

//*****MATCH CASE FOR LETTERS WHICH APPEAR MORE THAN ONCE IN THE STRING */

// var regex = /e/;
// var string = "Regex is great!"

// var result = string.match(regex);
// alert(result);

//  NB. AS IT IS, THIS WILL ONLY OUTPUT THE LETTER ONCE IN THE ALERT DIALOGUE (IF IT IS TRUE) TO CONFIRM THAT THE LETTER IS PRESENT IN THE STRING.
    // TO OUTPUT THE FULL NUMBER OF TRUE-CASE INSTANCES (ie. THE TOTAL TIMES THE REGEX VALUE APPEARS IN THE STRING), APPEND THE g FLAG (GLOBAL):

    var regex = /e/g;
    var string = "Regex is great!"

    var result = string.match(regex);
    alert(result);

    // THIS WILL OUTPUT e,e,e IN THIS TRUE INSTANCE OF MATCH CASE, IRRESPECTIVE OF WHERE IN THE STRING THE LETTERS ARE PRESENT. 
    // NO INSTANCE OF THE LETTER BEING CHECKED WILL RETURN A null, MUCH LIKE THE ABOVE